version: '3.8'

services:
  # Database Services
  pg:
    image: postgres:alpine
    container_name: chat-postgres
    restart: always
    ports:
      - "5480:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./chat-backend/drizzle/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=bita-dev
      - POSTGRES_PASSWORD=bita-dev-admin
      - POSTGRES_DB=test-db
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    shm_size: 128mb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U bita-dev -d test-db" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - chat-network

  # Backend Service
  chat-backend:
    build:
      context: ./chat-backend
      dockerfile: Dockerfile
    container_name: chat-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgresql://bita-dev:bita-dev-admin@pg:5432/test-db
      - DB_HOST=pg
      - DB_PORT=5432
      - DB_USER=bita-dev
      - DB_PASSWORD=bita-dev-admin
      - DB_NAME=test-db
      - JWT_SECRET=temporary-secret
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CORS_ORIGIN=http://localhost:3000
    depends_on:
      pg:
        condition: service_healthy

    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - chat-network

    volumes:
      - ./chat-backend:/app
      - backend_uploads:/app/uploads

  # Frontend Service
  chat-frontend:
    build:
      context: ./chat-frontend
      dockerfile: Dockerfile
    container_name: chat-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:3001
      - VITE_WS_URL=http://localhost:3001
    depends_on:
      chat-backend:
        condition: service_healthy
    volumes:
      - ./chat-frontend:/app
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge
    name: chat-network

volumes:
  medias:
    name: chat-medias
  static:
    name: chat-static
  pg_data:
    name: chat-postgres-data
  redis_data:
    name: chat-redis-data
  backend_uploads:
    name: chat-backend-uploads
